### ISSUE TITLE
[Q] I/O

### ISSUE THREAD

**Issue by Lanchon** [xgouchet/AXML#1]
hi,

thanks for sharing your code!

by any chance... do you happen to be aware of a library that both reads and writes binary xml?

thank you!

**Comment by xgouchet** [comment]
Hi, 

unfortunately no, I don't know of any such library. You can try to skim through the Android Framework source code, because they should have such a tool (but not sure what language it'll be in)

**Comment by Lanchon** [comment]
yes, reading is available in the framework, which is java. writing is available in aapt, which i'm guessing probably is C/C++, unfortunately. i wanted to sidestep going on that hunt. thanks!!

**Comment by Lanchon** [comment]
both aapt and aapt2 are wtitten in C++
https://github.com/android/platform_frameworks_base/tree/master/tools

**Comment by Lanchon** [comment]
and the reading in the Android framework is also native code!
https://github.com/android/platform_frameworks_base/blob/master/core/java/android/content/res/AssetManager.java#L854
